AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Handler: app.handler
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Layers:
      - !Ref DependenciesLayer
      - !Ref LibsLayer

Resources:
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/user-login
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        UserLogin:
          Type: HttpApi
          Properties:
            Path: /user-login
            Method: get
  HomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/home
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Home:
          Type: HttpApi
          Properties:
            Path: /home
            Method: get
  MineUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/mine-user
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        ReadItem:
          Type: HttpApi
          Properties:
            Path: /user
            Method: get
        UpdateItem:
          Type: HttpApi
          Properties:
            Path: /user
            Method: put
  MineAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/mine-account
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        CreateItem:
          Type: HttpApi
          Properties:
            Path: /accounts
            Method: put
        ReadItems:
          Type: HttpApi
          Properties:
            Path: /accounts
            Method: get
        UpdateItem:
          Type: HttpApi
          Properties:
            Path: /accounts/{id}
            Method: put
  MineCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/mine-category
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        CreateItem:
          Type: HttpApi
          Properties:
            Path: /categories
            Method: put
        ReadItems:
          Type: HttpApi
          Properties:
            Path: /categories
            Method: get
        UpdateItem:
          Type: HttpApi
          Properties:
            Path: /categories/{id}
            Method: put
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/dependencies
      CompatibleRuntimes: 
        - nodejs18.x
      CompatibleArchitectures:
        - arm64
    Metadata:
      BuildMethod: nodejs18.x
  LibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/libs
      CompatibleRuntimes: 
        - nodejs18.x
      CompatibleArchitectures:
        - arm64
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: app
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user
      AttributeDefinitions:
        - AttributeName: openid
          AttributeType: S
        - AttributeName: tokenCode
          AttributeType: S
        - AttributeName: loginDate
          AttributeType: N
      KeySchema:
        - AttributeName: openid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: tokenIndex
          KeySchema:
            - AttributeName: tokenCode
              KeyType: HASH
            - AttributeName: loginDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transaction
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createUser
          AttributeType: S
        - AttributeName: isDeleted
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: userIndex
          KeySchema:
            - AttributeName: createUser
              KeyType: HASH
            - AttributeName: isDeleted
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: account
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createUser
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: userIndex
          KeySchema:
            - AttributeName: createUser
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
  CategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: category
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createUser
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: userIndex
          KeySchema:
            - AttributeName: createUser
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2

Outputs:
  UserLoginApi:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/user-login/"
  UserLoginFunction:
    Value: !GetAtt UserLoginFunction.Arn
  UserLoginFunctionIamRole:
    Value: !GetAtt UserLoginFunctionRole.Arn
