AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 6
    Handler: app.handler
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Layers:
      - !Ref DependenciesLayer

Resources:
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-login/
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        UserLogin:
          Type: Api
          Properties:
            Path: /user-login
            Method: get
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/dependencies
      CompatibleRuntimes: 
        - nodejs18.x
      CompatibleArchitectures:
        - arm64
    Metadata:
      BuildMethod: nodejs18.x

  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: app
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user
      AttributeDefinitions:
        - AttributeName: openid
          AttributeType: S
      KeySchema:
        - AttributeName: openid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transaction
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  UserLoginApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/user-login/"
  UserLoginFunction:
    Value: !GetAtt UserLoginFunction.Arn
  UserLoginFunctionIamRole:
    Value: !GetAtt UserLoginFunctionRole.Arn
